apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app : my-k8s-application
spec:
  replicas: 2
  selector:
    matchLabels:
      project: kapp
  template:
    metadata:
      labels:
        project: kapp
    spec:
      containers:
        - name: kapp-web
          image: virus69virus69/my-web-app:1.0
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    env: prod
    owner: Slava
spec:
  selector:
    project: kapp
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
