apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app : my-k8s-application
spec:
  selector:
    matchLabels:
      project: kapp
  template:
    metadata:
      labels:
        project: kapp
    spec:
      containers:
        - name: kapp-web
          image: virus69virus69/my-web-app:2.0
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    env: prod
    owner: Slava
spec:
  selector:
    project: kapp
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 1
